### ISSUE TITLE
 Failure to "pip install" at 0.82a0

### ISSUE THREAD

**Issue by usebydh** [mixmastamyk/console#1]
Hi,

I want to install this module.
But I failed install, I have following error message.
---------------------
# pip install console
Collecting console
  Using cached https://files.pythonhosted.org/packages/38/9d/8f0c0f0b4926782c971ca1fa2bf5c769b58a4b77e1584ee59606e5ae84eb/console-0.82a0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g7ugum53/console/setup.py", line 9, in <module>
        from console.constants import __version__
      File "/tmp/pip-install-g7ugum53/console/console/__init__.py", line 24, in <module>
        from .detection import TermStack, choose_palette as _choose_palette
      File "/tmp/pip-install-g7ugum53/console/console/detection.py", line 324
        query_sequence = f'{OSC}{color_code};?{BEL}'
                                                   ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-g7ugum53/console/
#

**Comment by mixmastamyk** [comment]
Hi,
I'll look into it Monday.

Off the top of my head I'd guess you are trying to run it with a Python less than 3.6.  It currently requires that but could change if there's enough demand.

**Comment by usebydh** [comment]
Hi,
Thank you for your messages.
I see.

**Comment by mixmastamyk** [comment]
Hi, I tried adding the "future fstrings" package, which should now make it compatible with Py 3.5, you may want to try it.

**Comment by usebydh** [comment]
Thanks.
