### ISSUE TITLE
Alacritty on Windows conflates bold,bright attributes on detection

### ISSUE THREAD

**Issue by notaduck448** [mixmastamyk/console#8]

**Comment by mixmastamyk** [comment]
Hi,

Console does support bold and bright-color attributes as separate, however you may need to configure your terminal to disable the bright color when using bold.  The TERM variable may have some effect as well.

**Comment by notaduck448** [comment]
Apologies for not being more specific earlier.

The terminal I'm using is alacritty 0.5.0, and it does support separating bold text from bright text.

![image](https://user-images.githubusercontent.com/31483425/93830388-be09c900-fc35-11ea-9e7b-fc39ed61b102.png)

The problem arises after importing the library. After doing so, my terminal is no longer able to differentiate between bright and bold (even when not directly using the library to format the text).

![image](https://user-images.githubusercontent.com/31483425/93830609-45573c80-fc36-11ea-8f3d-265caf169e83.png)

**Comment by mixmastamyk** [comment]
Ok, I was writing a lot of speculation down and then it occurred to me.  It is not the second and third line that are wrong, it is the first.  In every line you turn on bold, but the first one doesn't acknowledge it for some reason.

Maybe it needs to be sent twice, I'm not certain.  Must be alacritty?  Wonder if it is using the old conhost or the new conpty stuff, I should try it myself this weekend.

There is also a troubleshooting part of the docs, but don't think it will help here:

    python -m console.demos -d

**Comment by mixmastamyk** [comment]
Perhaps the conhost probing console does on windows is affecting alacritty, I'm not sure.

I tried to run alacritty on my Win10 vm, but it refuses to run with "panicked re event loop".

**Comment by mixmastamyk** [comment]
I appear to be blocked by this:  https://github.com/alacritty/alacritty/issues/313

And I won't have access to a real Windows box any time soon.  

If you wanted to set the environment variable to avoid auto detection: `PY_CONSOLE_AUTODETECT=0` and create the fg, fx, etc objects yourself (see docs) you could.  Would be interesting to see if the problem still occurred.

If the issue no longer happens, starting normally (without the env variable) and commenting various parts of the detection would probably show where it happens.  Detection starts in detection.py and it loads windows-specific stuff from windows.py.

Somewhat tedious work however, for someone not working on it often.

**Comment by notaduck448** [comment]
I tried setting the environment variable PY_CONSOLE_AUTODETECT to 0 and discovered issue no longer occurs, meaning I can print bold and bright text separately.

Ill look through the detection module and see if I can figure out where the problem happens.

**Comment by mixmastamyk** [comment]
Perhaps the Windows function that enables "VT Processing" tickles some compatibility mode?

I'll try to reproduce it on other terminals on Windows this weekend and see if that has any effect.

**Comment by mixmastamyk** [comment]
Any luck?  I might not be able to see the changes myself, but could possibly introduce some temporary functionality like another variable to diagnose the behavior.  i.e. skip parts of detection.  It would also be helpful to know if alacritty "scrapes" a legacy console like older terminal apps on Windows, or uses the new ConPTY approach.

If the above variable pinpointed anything I could opt alacrittty out of it on Windows.  What does it use for the TERM* variables?

**Comment by mixmastamyk** [comment]
I added a check for `TERM=alacritty` on Windows before trying `enable_vt_processing()`.  Perhaps it will help, I'm kinda flying blind.

Will need to install the pre-release version with `pip install --pre -U console` to try.
